--[[
╔═══════════════════════════════════════════════════════════════════════════════════════════════════════════════╗
║                                                                                                               ║
║                                 AUTO-IMPORTED FRAMEWORK ITEMS                                                 ║
║                                                                                                               ║
║  This file is automatically generated by ox_inventory's framework item importer.                              ║
║  Items from your framework (RSGCore, QBCore, ESX, etc.) are imported here.                                    ║
║                                                                                                               ║
║      WARNING: This file is regenerated on resource restart if items change.                                   ║
║      Do not manually edit this file - changes will be overwritten.                                            ║
║      To customize an item, move its definition to the appropriate category file.                              ║
║                                                                                                               ║
║  On first start with RSG Core, items from rsg-core/shared/items.lua will be imported here automatically.      ║
║                                                                                                               ║
╚═══════════════════════════════════════════════════════════════════════════════════════════════════════════════╝
--]]

return {
    -- Items will be auto-imported here on resource start
    ["artichoke"] = {
        label = "Artichoke",
        weight = 100,
        stack = true,
        close = true,
        description = "A farm product",
        client = {
            image = "artichoke.png",
            usetime = 2500
        },
    },
    ["mutton"] = {
        label = "Mutton",
        weight = 800,
        stack = true,
        close = true,
        description = "Raw sheep meat",
        degrade = 0.0033333333333333,
        client = {
            image = "provision_meat_mature.png"
        },
    },
    ["injection_saline"] = {
        label = "Rope Tourniquet",
        weight = 100,
        stack = true,
        close = true,
        description = "Hydration and blood volume replacement - safe basic treatment",
        client = {
            image = "rope_tourniquet.png",
            usetime = 2500
        },
    },
    ["consumable_yeast"] = {
        label = "Yeast",
        weight = 50,
        stack = true,
        close = true,
        description = "Essential for fermentation",
        client = {
            image = "consumable_yeast.png"
        },
    },
    ["fossil_trilobite_crypto"] = {
        label = "Trilobite crypto Fossil",
        weight = 600,
        stack = true,
        close = true,
        description = "Archology Collectible",
        client = {
            image = "fossil_cryptolithus_trilobite.png",
            usetime = 2500
        },
    },
    ["canteen50"] = {
        label = "Canteen",
        weight = 300,
        stack = false,
        close = true,
        description = "Canteen 50% Full",
        client = {
            image = "canteen50.png",
            usetime = 2500
        },
    },
    ["sterile_band"] = {
        label = "Sterilized Gauze",
        weight = 0,
        stack = true,
        close = true,
        description = "A medical bandage for treating wounds",
        client = {
            image = "steril_gauze.png",
            usetime = 2500
        },
    },
    ["legendary_pelt"] = {
        label = "Legendary Pelt",
        weight = 100,
        stack = true,
        close = true,
        description = "Legendary",
        client = {
            image = "legendary_pelt.png",
            usetime = 2500
        },
    },
    ["duck_feathers"] = {
        label = "Duck Feathers",
        weight = 8,
        stack = true,
        close = true,
        description = "Waterproof duck feathers",
        client = {
            image = "feather.png"
        },
    },
    ["cotton_band"] = {
        label = "Cotton Bandage",
        weight = 0,
        stack = true,
        close = true,
        description = "A medical bandage for treating wounds",
        client = {
            image = "cotton_band.png",
            usetime = 2500
        },
    },
    ["consumable_moonshine_raspberry"] = {
        label = "Raspberry Moonshine",
        weight = 300,
        stack = true,
        close = true,
        description = "Tart raspberry moonshine",
        client = {
            image = "consumable_moonshine_raspberry.png",
            usetime = 2500
        },
    },
    ["duck_meat"] = {
        label = "Duck Meat",
        weight = 500,
        stack = true,
        close = true,
        description = "Raw duck meat",
        degrade = 0.0033333333333333,
        client = {
            image = "provision_meat_bird.png"
        },
    },
    ["crow_feathers"] = {
        label = "Crow Feathers",
        weight = 5,
        stack = true,
        close = true,
        description = "Black crow feathers",
        client = {
            image = "feather.png"
        },
    },
    ["still_build"] = {
        label = "Moonshine Still Kit",
        weight = 5000,
        stack = true,
        close = true,
        description = "A kit for building a moonshine distillery",
        client = {
            image = "still_build.png",
            usetime = 2500
        },
    },
    ["fox"] = {
        label = "Fox",
        weight = 900,
        stack = true,
        close = true,
        description = "Fox carcass",
        client = {
            image = "fox.png"
        },
    },
    ["injection_strychnine"] = {
        label = "Rope Tourniquet",
        weight = 100,
        stack = true,
        close = true,
        description = "Stimulant for paralysis and respiratory failure - extremely dangerous",
        client = {
            image = "rope_tourniquet.png",
            usetime = 2500
        },
    },
    ["fossil_tail_spike"] = {
        label = "Tail Spike Fossil",
        weight = 100,
        stack = true,
        close = true,
        description = "Archology Collectible",
        client = {
            image = "fossil_tail_spike.png",
            usetime = 2500
        },
    },
    ["trap_large"] = {
        label = "Large Animal Trap",
        weight = 1500,
        stack = true,
        close = true,
        description = "Catches large animals",
        client = {
            image = "trap_large.png",
            usetime = 2500
        },
    },
    ["raptor_meat"] = {
        label = "Raptor Meat",
        weight = 300,
        stack = true,
        close = true,
        description = "Raw hawk meat",
        degrade = 0.0033333333333333,
        client = {
            image = "provision_meat_bird.png"
        },
    },
    ["rabbit_meat"] = {
        label = "Rabbit Meat",
        weight = 300,
        stack = true,
        close = true,
        description = "Raw rabbit meat",
        degrade = 0.0033333333333333,
        client = {
            image = "provision_meat_exotic.png"
        },
    },
    ["carrion_bird_meat"] = {
        label = "Carrion Bird Meat",
        weight = 400,
        stack = true,
        close = true,
        description = "Raw vulture meat",
        degrade = 0.0033333333333333,
        client = {
            image = "provision_meat_bird.png"
        },
    },
    ["bear_meat"] = {
        label = "Bear Meat",
        weight = 2000,
        stack = true,
        close = true,
        description = "Raw bear meat",
        degrade = 0.0033333333333333,
        client = {
            image = "provision_meat_mature.png"
        },
    },
    ["cougar_claws"] = {
        label = "Cougar Claws",
        weight = 30,
        stack = true,
        close = true,
        description = "Sharp cougar claws",
        client = {
            image = "claw.png"
        },
    },
    ["iguana_meat"] = {
        label = "Iguana Meat",
        weight = 250,
        stack = true,
        close = true,
        description = "Raw iguana meat",
        degrade = 0.0033333333333333,
        client = {
            image = "provision_meat_exotic.png"
        },
    },
    ["fox_meat"] = {
        label = "Fox Meat",
        weight = 400,
        stack = true,
        close = true,
        description = "Raw fox meat",
        degrade = 0.0033333333333333,
        client = {
            image = "provision_meat_mature.png"
        },
    },
    ["sugarcube"] = {
        label = "Sugar Cube",
        weight = 100,
        stack = true,
        close = true,
        description = "Horses like these",
        client = {
            image = "sugarcube.png",
            usetime = 2500
        },
    },
    ["perfect_pelt"] = {
        label = "Perfect Pelt",
        weight = 100,
        stack = true,
        close = true,
        description = "Perfect (* * *)",
        client = {
            image = "perfect_pelt.png",
            usetime = 2500
        },
    },
    ["consumable_moonshine_alaskan"] = {
        label = "Alaskan Glow Moonshine",
        weight = 300,
        stack = true,
        close = true,
        description = "Berry-flavored moonshine from the north",
        client = {
            image = "consumable_moonshine_alaskan.png",
            usetime = 2500
        },
    },
    ["nails"] = {
        label = "Nails",
        weight = 20,
        stack = true,
        close = true,
        description = "Essential component for maintaining mechanic parts",
        client = {
            image = "nails.png"
        },
    },
    ["snake_skin"] = {
        label = "Snake Skin",
        weight = 200,
        stack = true,
        close = true,
        description = "Patterned snake skin",
        client = {
            image = "leather.png"
        },
    },
    ["bluecrab"] = {
        label = "Blue Crab",
        weight = 150,
        stack = true,
        close = true,
        description = "Fresh blue crab",
        client = {
            image = "bluecrab.png"
        },
    },
    ["heron_feathers"] = {
        label = "Heron Feathers",
        weight = 10,
        stack = true,
        close = true,
        description = "Elegant heron feathers",
        client = {
            image = "feather.png"
        },
    },
    ["coyote_meat"] = {
        label = "Coyote Meat",
        weight = 600,
        stack = true,
        close = true,
        description = "Raw coyote meat",
        degrade = 0.0033333333333333,
        client = {
            image = "provision_meat_mature.png"
        },
    },
    ["medicine_laudanum"] = {
        label = "Medicine Laudanum",
        weight = 100,
        stack = true,
        close = true,
        description = "Opium-based painkiller - powerful but addictive",
        client = {
            image = "medicine_laudanum.png",
            usetime = 2500
        },
    },
    ["cornseed"] = {
        label = "Corn seed",
        weight = 0,
        stack = true,
        close = true,
        description = "Used in agriculture",
        client = {
            image = "seed_corn.png",
            usetime = 2500
        },
    },
    ["tourniquet_leather"] = {
        label = "Leather Tourniquet",
        weight = 100,
        stack = true,
        close = true,
        description = "Emergency leather tourniquet for controlling severe bleeding",
        client = {
            image = "leather_tourniquet.png",
            usetime = 2500
        },
    },
    ["malina"] = {
        label = "Malina",
        weight = 100,
        stack = true,
        close = true,
        description = "A farm product",
        client = {
            image = "malina.png",
            usetime = 2500
        },
    },
    ["wolf_claws"] = {
        label = "Wolf Claws",
        weight = 25,
        stack = true,
        close = true,
        description = "Wolf claws",
        client = {
            image = "claw.png"
        },
    },
    ["buck_antlers"] = {
        label = "Buck Antlers",
        weight = 1000,
        stack = true,
        close = true,
        description = "Large buck antlers",
        client = {
            image = "antler.png"
        },
    },
    ["wheatseed"] = {
        label = "Wheat seed",
        weight = 0,
        stack = true,
        close = true,
        description = "Used in agriculture",
        client = {
            image = "seed_wheat.png",
            usetime = 2500
        },
    },
    ["fossil_old"] = {
        label = "Old Fossil",
        weight = 1000,
        stack = true,
        close = true,
        description = "Archology Collectible",
        client = {
            image = "fossil_tully_monster.png",
            usetime = 2500
        },
    },
    ["skunk"] = {
        label = "Skunk",
        weight = 600,
        stack = true,
        close = true,
        description = "Skunk carcass",
        client = {
            image = "skunk.png"
        },
    },
    ["trapbait"] = {
        label = "Trap Bait",
        weight = 50,
        stack = true,
        close = true,
        description = "Bait for animal traps",
        client = {
            image = "trapbait.png"
        },
    },
    ["feather"] = {
        label = "Feather",
        weight = 100,
        stack = true,
        close = true,
        description = "bird feather",
        client = {
            image = "feather.png",
            usetime = 2500
        },
    },
    ["consumable_moonshine_apple_crumb"] = {
        label = "Apple Pie Moonshine",
        weight = 300,
        stack = true,
        close = true,
        description = "Sweet apple pie flavored moonshine",
        client = {
            image = "consumable_moonshine_apple_crumb.png",
            usetime = 2500
        },
    },
    ["moonshine_pipe"] = {
        label = "Moonshine Pipe",
        weight = 500,
        stack = true,
        close = true,
        description = "Copper pipe for moonshine distillation",
        client = {
            image = "moonshine_pipe.png"
        },
    },
    ["fieldbandage"] = {
        label = "Field Bandage",
        weight = 100,
        stack = true,
        close = true,
        description = "patching yourself up",
        client = {
            image = "fieldbandage.png",
            usetime = 2500
        },
    },
    ["wolf_fangs"] = {
        label = "Wolf Fangs",
        weight = 20,
        stack = true,
        close = true,
        description = "Sharp wolf fangs",
        client = {
            image = "tooth.png"
        },
    },
    ["fossil_brachiopod"] = {
        label = "Brachiopod Fossil",
        weight = 1000,
        stack = true,
        close = true,
        description = "Archology Collectible",
        client = {
            image = "fossil_brachiopod.png",
            usetime = 2500
        },
    },
    ["coyote"] = {
        label = "Coyote",
        weight = 1200,
        stack = true,
        close = true,
        description = "Coyote carcass",
        client = {
            image = "coyote.png"
        },
    },
    ["bear_fangs"] = {
        label = "Bear Fangs",
        weight = 30,
        stack = true,
        close = true,
        description = "Large bear fangs",
        client = {
            image = "tooth.png"
        },
    },
    ["reptile_skin"] = {
        label = "Reptile Skin",
        weight = 100,
        stack = true,
        close = true,
        description = "snake skin",
        client = {
            image = "reptile_skin.png",
            usetime = 2500
        },
    },
    ["canteen75"] = {
        label = "Canteen",
        weight = 400,
        stack = false,
        close = true,
        description = "Canteen 75% Full",
        client = {
            image = "canteen75.png",
            usetime = 2500
        },
    },
    ["fossil_cephalopod"] = {
        label = "Cephalopod Fossil",
        weight = 2000,
        stack = true,
        close = true,
        description = "Archology Collectible",
        client = {
            image = "fossil_cephalopod.png",
            usetime = 2500
        },
    },
    ["gunsmith"] = {
        label = "Gun craft",
        weight = 12000,
        stack = true,
        close = true,
        description = "Placeholder",
        client = {
            image = "guncraft.png",
            usetime = 2500
        },
    },
    ["crane_feathers"] = {
        label = "Crane Feathers",
        weight = 12,
        stack = true,
        close = true,
        description = "Long crane feathers",
        client = {
            image = "feather.png"
        },
    },
    ["turkey_feathers"] = {
        label = "Turkey Feathers",
        weight = 12,
        stack = true,
        close = true,
        description = "Wild turkey feathers",
        client = {
            image = "feather.png"
        },
    },
    ["bandage"] = {
        label = "Bandage",
        weight = 100,
        stack = true,
        close = true,
        description = "used to improve your health",
        client = {
            image = "bandage.png",
            usetime = 2500
        },
    },
    ["condor_feathers"] = {
        label = "Condor Feathers",
        weight = 20,
        stack = true,
        close = true,
        description = "Rare condor feathers",
        client = {
            image = "feather.png"
        },
    },
    ["canteen100"] = {
        label = "Full Canteen",
        weight = 500,
        stack = false,
        close = true,
        description = "Canteen 100% Full",
        client = {
            image = "canteen100.png",
            usetime = 2500
        },
    },
    ["consumable_mash_tropical_punch"] = {
        label = "Tropical Punch Mash",
        weight = 500,
        stack = true,
        close = true,
        description = "Exotic fruit mash blend",
        client = {
            image = "consumable_mash_tropical_punch.png"
        },
    },
    ["coal_ore"] = {
        label = "Coal",
        weight = 100,
        stack = true,
        close = true,
        description = "Used as fuel for stills",
        client = {
            image = "coal_ore.png"
        },
    },
    ["consumable_mash_plum"] = {
        label = "Plum Mash",
        weight = 500,
        stack = true,
        close = true,
        description = "Rich plum-flavored mash",
        client = {
            image = "consumable_mash_plum.png"
        },
    },
    ["horse_brush"] = {
        label = "Horse Brush",
        weight = 100,
        stack = true,
        close = true,
        description = "brush used to clean your horse",
        client = {
            image = "horse_brush.png",
            usetime = 2500
        },
    },
    ["injection_cocaine"] = {
        label = "Rope Tourniquet",
        weight = 100,
        stack = true,
        close = true,
        description = "Local anesthetic for surgical procedures - numbs pain effectively",
        client = {
            image = "rope_tourniquet.png",
            usetime = 2500
        },
    },
    ["horse_lantern"] = {
        label = "Horse Lantern",
        weight = 100,
        stack = true,
        close = true,
        description = "to see in the dark",
        client = {
            image = "horse_lantern.png",
            usetime = 2500
        },
    },
    ["boar_meat"] = {
        label = "Boar Meat",
        weight = 1200,
        stack = true,
        close = true,
        description = "Raw boar meat",
        degrade = 0.0033333333333333,
        client = {
            image = "provision_meat_mature.png"
        },
    },
    ["gator_claws"] = {
        label = "Alligator Claws",
        weight = 40,
        stack = true,
        close = true,
        description = "Alligator claws",
        client = {
            image = "claw.png"
        },
    },
    ["cougar_fangs"] = {
        label = "Cougar Fangs",
        weight = 20,
        stack = true,
        close = true,
        description = "Sharp cougar fangs",
        client = {
            image = "tooth.png"
        },
    },
    ["owl_feathers"] = {
        label = "Owl Feathers",
        weight = 15,
        stack = true,
        close = true,
        description = "Soft owl feathers",
        client = {
            image = "feather.png"
        },
    },
    ["hoe"] = {
        label = "Farm Hoe",
        weight = 200,
        stack = true,
        close = true,
        description = "A farming tool used for planting seeds",
        client = {
            image = "hoe.png"
        },
    },
    ["dollar"] = {
        label = "Dollars",
        weight = 1,
        stack = true,
        close = true,
        description = "Standard currency used for everyday transactions",
        client = {
            image = "dollar.png"
        },
    },
    ["rat_meat"] = {
        label = "Rat Meat",
        weight = 100,
        stack = true,
        close = true,
        description = "Raw rat meat",
        degrade = 0.0033333333333333,
        client = {
            image = "provision_meat_exotic.png"
        },
    },
    ["water_bird_meat"] = {
        label = "Water Bird Meat",
        weight = 500,
        stack = true,
        close = true,
        description = "Raw water bird meat",
        degrade = 0.0033333333333333,
        client = {
            image = "provision_meat_bird.png"
        },
    },
    ["eagle_feathers"] = {
        label = "Eagle Feathers",
        weight = 20,
        stack = true,
        close = true,
        description = "Pristine eagle feathers",
        client = {
            image = "feather.png"
        },
    },
    ["medicine_morphine"] = {
        label = "Medicine Morphine",
        weight = 100,
        stack = true,
        close = true,
        description = "Powerful opiate analgesic - strongest painkiller available",
        client = {
            image = "medicine_morphine.png",
            usetime = 2500
        },
    },
    ["dinosaur_egg"] = {
        label = "Dinosaur Egg Fossil",
        weight = 300,
        stack = true,
        close = true,
        description = "Archology Collectible",
        client = {
            image = "fossil_dinosaur_egg.png",
            usetime = 2500
        },
    },
    ["pronghorn_horns"] = {
        label = "Pronghorn Horns",
        weight = 600,
        stack = true,
        close = true,
        description = "Pronghorn horns",
        client = {
            image = "antler.png"
        },
    },
    ["tomatoseed"] = {
        label = "Tomato seed",
        weight = 0,
        stack = true,
        close = true,
        description = "Used in agriculture",
        client = {
            image = "seed_tomato.png",
            usetime = 2500
        },
    },
    ["money_clip"] = {
        label = "Money Clip",
        weight = 1,
        stack = false,
        close = true,
        description = "Money Clip",
        client = {
            image = "money_clip.png",
            usetime = 2500
        },
    },
    ["sugarseed"] = {
        label = "Sugar seed",
        weight = 0,
        stack = true,
        close = true,
        description = "Used in agriculture",
        client = {
            image = "seed_sugar_cane.png",
            usetime = 2500
        },
    },
    ["consumable_moonshine_peach"] = {
        label = "Peach Moonshine",
        weight = 300,
        stack = true,
        close = true,
        description = "Sweet peach moonshine",
        client = {
            image = "consumable_moonshine_peach.png",
            usetime = 2500
        },
    },
    ["consumable_moonshine_wild_cider"] = {
        label = "Wild Creek Moonshine",
        weight = 300,
        stack = true,
        close = true,
        description = "Wild crabapple honey moonshine",
        client = {
            image = "consumable_moonshine_wild_cider.png",
            usetime = 2500
        },
    },
    ["metal_components"] = {
        label = "Metal Components",
        weight = 100,
        stack = true,
        close = true,
        description = "Various metal parts for repairs and upgrades",
        client = {
            image = "metal_components.png"
        },
    },
    ["bison_meat"] = {
        label = "Bison Meat",
        weight = 2500,
        stack = true,
        close = true,
        description = "Raw bison meat",
        degrade = 0.0033333333333333,
        client = {
            image = "provision_meat_mature.png"
        },
    },
    ["bison_horns"] = {
        label = "Bison Horns",
        weight = 1200,
        stack = true,
        close = true,
        description = "Large bison horns",
        client = {
            image = "antler.png"
        },
    },
    ["consumable_moonshine_tropical_punch"] = {
        label = "Tropical Punch Moonshine",
        weight = 300,
        stack = true,
        close = true,
        description = "Exotic tropical fruit moonshine",
        client = {
            image = "consumable_moonshine_tropical_punch.png",
            usetime = 2500
        },
    },
    ["hawk_feathers"] = {
        label = "Hawk Feathers",
        weight = 15,
        stack = true,
        close = true,
        description = "Sharp hawk feathers",
        client = {
            image = "feather.png"
        },
    },
    ["poultry"] = {
        label = "Poultry",
        weight = 400,
        stack = true,
        close = true,
        description = "Raw chicken meat",
        degrade = 0.0033333333333333,
        client = {
            image = "provision_meat_bird.png"
        },
    },
    ["archeology_book"] = {
        label = "Archeology Book",
        weight = 10,
        stack = false,
        close = true,
        description = "Book for all your archeology needs",
        client = {
            image = "archeology_book.png",
            usetime = 2500
        },
    },
    ["vulture_feathers"] = {
        label = "Vulture Feathers",
        weight = 15,
        stack = true,
        close = true,
        description = "Dark vulture feathers",
        client = {
            image = "feather.png"
        },
    },
    ["consumable_alcohol_moonshine"] = {
        label = "Basic Moonshine",
        weight = 300,
        stack = true,
        close = true,
        description = "Strong homemade moonshine",
        client = {
            image = "consumable_alcohol_moonshine.png",
            usetime = 2500
        },
    },
    ["pronghorn_meat"] = {
        label = "Pronghorn Meat",
        weight = 1200,
        stack = true,
        close = true,
        description = "Raw pronghorn meat",
        degrade = 0.0033333333333333,
        client = {
            image = "provision_meat_mature.png"
        },
    },
    ["fossil_pet_wood"] = {
        label = "Wood Fossil",
        weight = 800,
        stack = true,
        close = true,
        description = "Archology Collectible",
        client = {
            image = "fossil_common_petrified_wood.png",
            usetime = 2500
        },
    },
    ["moonshine_barrel"] = {
        label = "Moonshine Barrel",
        weight = 2000,
        stack = true,
        close = true,
        description = "A large barrel for fermenting mash",
        client = {
            image = "moonshine_barrel.png"
        },
    },
    ["gator_skin"] = {
        label = "Alligator Skin",
        weight = 1500,
        stack = true,
        close = true,
        description = "Tough alligator hide",
        client = {
            image = "leather.png"
        },
    },
    ["poor_pelt"] = {
        label = "Poor Pelt",
        weight = 100,
        stack = true,
        close = true,
        description = "Poor (*)",
        client = {
            image = "poor_pelt.png",
            usetime = 2500
        },
    },
    ["crow_meat"] = {
        label = "Crow Meat",
        weight = 150,
        stack = true,
        close = true,
        description = "Raw crow meat",
        degrade = 0.0033333333333333,
        client = {
            image = "provision_meat_bird.png"
        },
    },
    ["arrowhead_bone"] = {
        label = "Arrowhead Bone",
        weight = 100,
        stack = true,
        close = true,
        description = "Archology Collectible",
        client = {
            image = "fossil_arrowhead_bone.png",
            usetime = 2500
        },
    },
    ["consumable_mash_apple_crumb"] = {
        label = "Apple Crumb Mash",
        weight = 500,
        stack = true,
        close = true,
        description = "Sweet apple and cinnamon mash",
        client = {
            image = "consumable_mash_apple_crumb.png"
        },
    },
    ["venison"] = {
        label = "Venison",
        weight = 1500,
        stack = true,
        close = true,
        description = "Raw deer meat",
        degrade = 0.0033333333333333,
        client = {
            image = "provision_meat_mature.png"
        },
    },
    ["goose_feathers"] = {
        label = "Goose Feathers",
        weight = 10,
        stack = true,
        close = true,
        description = "Soft goose feathers",
        client = {
            image = "feather.png"
        },
    },
    ["moonshine_pot_distillery"] = {
        label = "Distillery Pot",
        weight = 1500,
        stack = true,
        close = true,
        description = "Essential pot for distilling moonshine",
        client = {
            image = "moonshine_pot_distillery.png"
        },
    },
    ["fossil_sea_scorpion"] = {
        label = "Sea Scorpion Fossil",
        weight = 500,
        stack = true,
        close = true,
        description = "Archology Collectible",
        client = {
            image = "fossil_sea_scorpion.png",
            usetime = 2500
        },
    },
    ["owl_meat"] = {
        label = "Owl Meat",
        weight = 250,
        stack = true,
        close = true,
        description = "Raw owl meat",
        degrade = 0.0033333333333333,
        client = {
            image = "provision_meat_bird.png"
        },
    },
    ["cent"] = {
        label = "Cents",
        weight = 3,
        stack = true,
        close = true,
        description = "Small denomination of currency, commonly used for change",
        client = {
            image = "cent.png"
        },
    },
    ["blood_dollar"] = {
        label = "Bloodstained Dollars",
        weight = 1,
        stack = true,
        close = true,
        description = "Currency tainted by violence and crime",
        client = {
            image = "blood_dollar.png"
        },
    },
    ["rabbit"] = {
        label = "Rabbit",
        weight = 500,
        stack = true,
        close = true,
        description = "Rabbit carcass",
        client = {
            image = "rabbit.png"
        },
    },
    ["fossil_trilobit"] = {
        label = "Trilobit Fossil",
        weight = 400,
        stack = true,
        close = true,
        description = "Archology Collectible",
        client = {
            image = "fossil_isotelus_trilobite.png",
            usetime = 2500
        },
    },
    ["chicken_feathers"] = {
        label = "Chicken Feathers",
        weight = 5,
        stack = true,
        close = true,
        description = "Common chicken feathers",
        client = {
            image = "feather.png"
        },
    },
    ["consumable_mash_american"] = {
        label = "American Mash",
        weight = 500,
        stack = true,
        close = true,
        description = "Classic American-style corn and wheat mash",
        client = {
            image = "consumable_mash_american.png"
        },
    },
    ["fossil_tooth_serrated"] = {
        label = "Serrated Tooth v",
        weight = 40,
        stack = true,
        close = true,
        description = "Archology Collectible",
        client = {
            image = "fossil_tooth_serrated.png",
            usetime = 2500
        },
    },
    ["squirrel"] = {
        label = "Squirrel",
        weight = 200,
        stack = true,
        close = true,
        description = "Squirrel carcass",
        client = {
            image = "squirrel.png"
        },
    },
    ["linen_band"] = {
        label = "Linen Wrap",
        weight = 0,
        stack = true,
        close = true,
        description = "A medical bandage for treating wounds",
        client = {
            image = "linen_wrap.png",
            usetime = 2500
        },
    },
    ["consumable_potent_predator_bait"] = {
        label = "Potent Predator Bait",
        weight = 100,
        stack = true,
        close = true,
        description = "Potent bait for predators",
        client = {
            image = "consumable_potent_predator_bait.png",
            usetime = 2500
        },
    },
    ["good_pelt"] = {
        label = "Good Pelt",
        weight = 100,
        stack = true,
        close = true,
        description = "Good (* *)",
        client = {
            image = "good_pelt.png",
            usetime = 2500
        },
    },
    ["pheasant_feathers"] = {
        label = "Pheasant Feathers",
        weight = 8,
        stack = true,
        close = true,
        description = "Colorful pheasant feathers",
        client = {
            image = "feather.png"
        },
    },
    ["bear_claws"] = {
        label = "Bear Claws",
        weight = 50,
        stack = true,
        close = true,
        description = "Sharp bear claws",
        client = {
            image = "claw.png"
        },
    },
    ["deer_antlers"] = {
        label = "Deer Antlers",
        weight = 800,
        stack = true,
        close = true,
        description = "Deer antlers",
        client = {
            image = "antler.png"
        },
    },
    ["game_bird_meat"] = {
        label = "Game Bird Meat",
        weight = 600,
        stack = true,
        close = true,
        description = "Raw game bird meat",
        degrade = 0.0033333333333333,
        client = {
            image = "provision_meat_bird.png"
        },
    },
    ["consumable_potent_herbivore_bait"] = {
        label = "Potent Herbivore Bait",
        weight = 100,
        stack = true,
        close = true,
        description = "Potent bait for herbivores",
        client = {
            image = "consumable_potent_herbivore_bait.png",
            usetime = 2500
        },
    },
    ["consumable_mash_wild_cider"] = {
        label = "Wild Cider Mash",
        weight = 500,
        stack = true,
        close = true,
        description = "Wild crabapple and honey mash",
        client = {
            image = "consumable_mash_wild_cider.png"
        },
    },
    ["horse_reviver"] = {
        label = "Horse Reviver",
        weight = 100,
        stack = true,
        close = true,
        description = "Given to horses",
        client = {
            image = "horse_reviver.png",
            usetime = 2500
        },
    },
    ["rooster_feathers"] = {
        label = "Rooster Feathers",
        weight = 6,
        stack = true,
        close = true,
        description = "Colorful rooster feathers",
        client = {
            image = "feather.png"
        },
    },
    ["stew"] = {
        label = "Stew",
        weight = 100,
        stack = true,
        close = true,
        description = "Warm Stew",
        degrade = 0.016666666666667,
        client = {
            image = "consumable_stew_prison.png",
            usetime = 2500
        },
    },
    ["fullbucket"] = {
        label = "Bucket full",
        weight = 50.0,
        stack = true,
        close = true,
        description = "Bucket full of  water for plants",
        client = {
            image = "bucket.png",
            usetime = 2500
        },
    },
    ["lobster"] = {
        label = "Lobster",
        weight = 300,
        stack = true,
        close = true,
        description = "Fresh lobster",
        client = {
            image = "lobster.png"
        },
    },
    ["pelican_feathers"] = {
        label = "Pelican Feathers",
        weight = 15,
        stack = true,
        close = true,
        description = "White pelican feathers",
        client = {
            image = "feather.png"
        },
    },
    ["fossil_tooth_mega"] = {
        label = "Mega Tooth Fossil",
        weight = 80,
        stack = true,
        close = true,
        description = "Archology Collectible",
        client = {
            image = "fossil_tooth_upper.png",
            usetime = 2500
        },
    },
    ["goat_horns"] = {
        label = "Goat Horns",
        weight = 400,
        stack = true,
        close = true,
        description = "Mountain goat horns",
        client = {
            image = "antler.png"
        },
    },
    ["consumable_mash_peach"] = {
        label = "Peach Mash",
        weight = 500,
        stack = true,
        close = true,
        description = "Sweet peach-infused mash",
        client = {
            image = "consumable_mash_peach.png"
        },
    },
    ["fossil_pet_wood_yellow_cat"] = {
        label = "Wood Yellow Cat Fossil",
        weight = 1000,
        stack = true,
        close = true,
        description = "Archology Collectible",
        client = {
            image = "fossil_yellowcat_petrified_wood.png",
            usetime = 2500
        },
    },
    ["beaver_meat"] = {
        label = "Beaver Meat",
        weight = 500,
        stack = true,
        close = true,
        description = "Raw beaver meat",
        degrade = 0.0033333333333333,
        client = {
            image = "provision_meat_exotic.png"
        },
    },
    ["consumable_predator_bait"] = {
        label = "Predator Bait",
        weight = 100,
        stack = true,
        close = true,
        description = "Attracts predators",
        client = {
            image = "consumable_predator_bait.png",
            usetime = 2500
        },
    },
    ["cloth_band"] = {
        label = "Cloth Strip",
        weight = 0,
        stack = true,
        close = true,
        description = "A medical bandage for treating wounds",
        client = {
            image = "cloth_strip.png",
            usetime = 2500
        },
    },
    ["gator_tooth"] = {
        label = "Alligator Tooth",
        weight = 25,
        stack = true,
        close = true,
        description = "Alligator tooth",
        client = {
            image = "tooth.png"
        },
    },
    ["trap_medium"] = {
        label = "Medium Animal Trap",
        weight = 1000,
        stack = true,
        close = true,
        description = "Catches medium animals",
        client = {
            image = "trap_medium.png",
            usetime = 2500
        },
    },
    ["canteen25"] = {
        label = "Canteen",
        weight = 200,
        stack = false,
        close = true,
        description = "Canteen 25% Full",
        client = {
            image = "canteen25.png",
            usetime = 2500
        },
    },
    ["canteen0"] = {
        label = "Empty Canteen",
        weight = 100,
        stack = false,
        close = true,
        description = "Empty Canteen",
        client = {
            image = "canteen0.png",
            usetime = 2500
        },
    },
    ["tourniquet_rope"] = {
        label = "Rope Tourniquet",
        weight = 100,
        stack = true,
        close = true,
        description = "Emergency rope tourniquet for controlling severe bleeding",
        client = {
            image = "rope_tourniquet.png",
            usetime = 2500
        },
    },
    ["crayfish"] = {
        label = "Crayfish",
        weight = 100,
        stack = true,
        close = true,
        description = "Fresh crayfish",
        client = {
            image = "crayfish.png"
        },
    },
    ["injection_adrenaline"] = {
        label = "Rope Tourniquet",
        weight = 100,
        stack = true,
        close = true,
        description = "Cardiac stimulant for emergency resuscitation - use with extreme caution",
        client = {
            image = "rope_tourniquet.png",
            usetime = 2500
        },
    },
    ["bigcat_meat"] = {
        label = "Big Cat Meat",
        weight = 1500,
        stack = true,
        close = true,
        description = "Raw cougar meat",
        degrade = 0.0033333333333333,
        client = {
            image = "provision_meat_mature.png"
        },
    },
    ["consumable_mash_blackberry"] = {
        label = "Blackberry Mash",
        weight = 500,
        stack = true,
        close = true,
        description = "Dark berry mash with rich flavor",
        client = {
            image = "consumable_mash_blackberry.png"
        },
    },
    ["bnuts"] = {
        label = "Bolt Nuts",
        weight = 10,
        stack = true,
        close = true,
        description = "Nuts for bolts",
        client = {
            image = "bnuts.png"
        },
    },
    ["badger"] = {
        label = "Badger",
        weight = 1000,
        stack = true,
        close = true,
        description = "Badger carcass",
        client = {
            image = "badger.png"
        },
    },
    ["animal_heart"] = {
        label = "Animal Heart",
        weight = 100,
        stack = true,
        close = true,
        description = "animal heart",
        degrade = 0.0055555555555556,
        client = {
            image = "animal_heart.png",
            usetime = 2500
        },
    },
    ["artichokeseed"] = {
        label = "Artichoke seed",
        weight = 0,
        stack = true,
        close = true,
        description = "Used in agriculture",
        client = {
            image = "artichokeseed.png",
            usetime = 2500
        },
    },
    ["raccoon_meat"] = {
        label = "Raccoon Meat",
        weight = 250,
        stack = true,
        close = true,
        description = "Raw raccoon meat",
        degrade = 0.0033333333333333,
        client = {
            image = "provision_meat_exotic.png"
        },
    },
    ["fossil_brow_horn"] = {
        label = "Brow Horn Fossil",
        weight = 1200,
        stack = true,
        close = true,
        description = "Archology Collectible",
        client = {
            image = "fossil_brow_horn.png",
            usetime = 2500
        },
    },
    ["moonshine_empty_jug"] = {
        label = "Empty Jug",
        weight = 200,
        stack = true,
        close = true,
        description = "Empty jug for storing moonshine",
        client = {
            image = "moonshine_empty_jug.png"
        },
    },
    ["snake_meat"] = {
        label = "Snake Meat",
        weight = 200,
        stack = true,
        close = true,
        description = "Raw snake meat",
        degrade = 0.0033333333333333,
        client = {
            image = "provision_meat_exotic.png"
        },
    },
    ["potatoseed"] = {
        label = "Potato seed",
        weight = 0,
        stack = true,
        close = true,
        description = "Used in agriculture",
        client = {
            image = "seed_potato.png",
            usetime = 2500
        },
    },
    ["turtle_shell"] = {
        label = "Turtle Shell",
        weight = 800,
        stack = true,
        close = true,
        description = "Hard turtle shell",
        client = {
            image = "turtle_shell.png"
        },
    },
    ["quail_feathers"] = {
        label = "Quail Feathers",
        weight = 5,
        stack = true,
        close = true,
        description = "Small quail feathers",
        client = {
            image = "feather.png"
        },
    },
    ["fishtrap"] = {
        label = "Fish Trap",
        weight = 800,
        stack = true,
        close = true,
        description = "Catches fish and crustaceans",
        client = {
            image = "fishtrap.png",
            usetime = 2500
        },
    },
    ["raven_feathers"] = {
        label = "Raven Feathers",
        weight = 6,
        stack = true,
        close = true,
        description = "Glossy raven feathers",
        client = {
            image = "feather.png"
        },
    },
    ["consumable_herbivore_bait"] = {
        label = "Herbivore Bait",
        weight = 100,
        stack = true,
        close = true,
        description = "Attracts herbivores",
        client = {
            image = "consumable_herbivore_bait.png",
            usetime = 2500
        },
    },
    ["tourniquet_medical"] = {
        label = "Medical Tourniquet",
        weight = 100,
        stack = true,
        close = true,
        description = "Emergency medical tourniquet for controlling severe bleeding",
        client = {
            image = "medical_tourniquet.png",
            usetime = 2500
        },
    },
    ["fossil_coral"] = {
        label = "Coral Fossil Fossil",
        weight = 1400,
        stack = true,
        close = true,
        description = "Archology Collectible",
        client = {
            image = "fossil_agatized_coral.png",
            usetime = 2500
        },
    },
    ["crab"] = {
        label = "Crab",
        weight = 150,
        stack = true,
        close = true,
        description = "Fresh crab",
        client = {
            image = "crab.png"
        },
    },
    ["firstaid"] = {
        label = "First Aid",
        weight = 100,
        stack = true,
        close = true,
        description = "used by medics to improve your health",
        client = {
            image = "firstaid.png",
            usetime = 2500
        },
    },
    ["fossil_bivalve"] = {
        label = "Bivalve Fossil",
        weight = 500,
        stack = true,
        close = true,
        description = "Archology Collectible",
        client = {
            image = "fossil_bivalve.png",
            usetime = 2500
        },
    },
    ["blood_cent"] = {
        label = "Bloodstained Cents",
        weight = 3,
        stack = true,
        close = true,
        description = "Small change stained with the remnants of bloodshed",
        client = {
            image = "blood_cent.png"
        },
    },
    ["blood_money_clip"] = {
        label = "Blood Money Clip",
        weight = 1,
        stack = false,
        close = true,
        description = "Blood Money Clip",
        client = {
            image = "blood_money_clip.png",
            usetime = 2500
        },
    },
    ["snake_fangs"] = {
        label = "Snake Fangs",
        weight = 10,
        stack = true,
        close = true,
        description = "Venomous snake fangs",
        client = {
            image = "tooth.png"
        },
    },
    ["armadillo_shell"] = {
        label = "Armadillo Shell",
        weight = 600,
        stack = true,
        close = true,
        description = "Armored shell",
        client = {
            image = "turtle_shell.png"
        },
    },
    ["fossil_toe_claw"] = {
        label = "Claw Fossil",
        weight = 120,
        stack = true,
        close = true,
        description = "Archology Collectible",
        client = {
            image = "fossil_toe_sickle_claw.png",
            usetime = 2500
        },
    },
    ["consumable_mash_alaskan"] = {
        label = "Alaskan Mash",
        weight = 500,
        stack = true,
        close = true,
        description = "Berry-infused mash from the north",
        client = {
            image = "consumable_mash_alaskan.png"
        },
    },
    ["gator_meat"] = {
        label = "Alligator Meat",
        weight = 1800,
        stack = true,
        close = true,
        description = "Raw gator meat",
        degrade = 0.0033333333333333,
        client = {
            image = "provision_meat_mature.png"
        },
    },
    ["goat_meat"] = {
        label = "Goat Meat",
        weight = 700,
        stack = true,
        close = true,
        description = "Raw goat meat",
        degrade = 0.0033333333333333,
        client = {
            image = "provision_meat_mature.png"
        },
    },
    ["ram_horns"] = {
        label = "Ram Horns",
        weight = 900,
        stack = true,
        close = true,
        description = "Bighorn ram horns",
        client = {
            image = "antler.png"
        },
    },
    ["consumable_mash_raspberry"] = {
        label = "Raspberry Mash",
        weight = 500,
        stack = true,
        close = true,
        description = "Tart raspberry mash",
        client = {
            image = "consumable_mash_raspberry.png"
        },
    },
    ["tourniquet_cloth"] = {
        label = "Cloth Tourniquet",
        weight = 100,
        stack = true,
        close = true,
        description = "Emergency cloth tourniquet for controlling severe bleeding",
        client = {
            image = "cloth_tourniquet.png",
            usetime = 2500
        },
    },
    ["opossum_meat"] = {
        label = "Opossum Meat",
        weight = 200,
        stack = true,
        close = true,
        description = "Raw opossum meat",
        degrade = 0.0033333333333333,
        client = {
            image = "provision_meat_exotic.png"
        },
    },
    ["consumable_moonshine_blackberry"] = {
        label = "Blackberry Moonshine",
        weight = 300,
        stack = true,
        close = true,
        description = "Rich blackberry moonshine",
        client = {
            image = "consumable_moonshine_blackberry.png",
            usetime = 2500
        },
    },
    ["rat"] = {
        label = "Rat",
        weight = 200,
        stack = true,
        close = true,
        description = "Rat carcass",
        client = {
            image = "rat.png"
        },
    },
    ["frog_meat"] = {
        label = "Frog Legs",
        weight = 100,
        stack = true,
        close = true,
        description = "Raw frog legs",
        degrade = 0.0033333333333333,
        client = {
            image = "provision_meat_exotic.png"
        },
    },
    ["moonshine_condenser"] = {
        label = "Moonshine Condenser",
        weight = 800,
        stack = true,
        close = true,
        description = "Condenser coil for distilling process",
        client = {
            image = "moonshine_condenser.png"
        },
    },
    ["finger_bone"] = {
        label = "Finger Bone Fossil",
        weight = 200,
        stack = true,
        close = true,
        description = "Archology Collectible",
        client = {
            image = "fossil_finger_bone.png",
            usetime = 2500
        },
    },
    ["raccoon"] = {
        label = "Raccoon",
        weight = 800,
        stack = true,
        close = true,
        description = "Raccoon carcass",
        client = {
            image = "raccoon.png"
        },
    },
    ["chipmunk"] = {
        label = "Chipmunk",
        weight = 150,
        stack = true,
        close = true,
        description = "Chipmunk carcass",
        client = {
            image = "chipmunk.png"
        },
    },
    ["tobaccoseed"] = {
        label = "Tobacco seed",
        weight = 0,
        stack = true,
        close = true,
        description = "Used in agriculture",
        client = {
            image = "seed_indian_tobacco.png",
            usetime = 2500
        },
    },
    ["consumable_moonshine_plum"] = {
        label = "Plum Moonshine",
        weight = 300,
        stack = true,
        close = true,
        description = "Rich plum moonshine",
        client = {
            image = "consumable_moonshine_plum.png",
            usetime = 2500
        },
    },
    ["malinaseed"] = {
        label = "Malina Seed",
        weight = 0,
        stack = true,
        close = true,
        description = "Used in agriculture",
        client = {
            image = "malinaseed.png",
            usetime = 2500
        },
    },
    ["small_bird_meat"] = {
        label = "Small Bird Meat",
        weight = 250,
        stack = true,
        close = true,
        description = "Raw small bird meat",
        degrade = 0.0033333333333333,
        client = {
            image = "provision_meat_bird.png"
        },
    },
    ["fossil_neo"] = {
        label = "Neo Fossil",
        weight = 2400,
        stack = true,
        close = true,
        description = "Archology Collectible",
        client = {
            image = "fossil_neospirifer.png",
            usetime = 2500
        },
    },
    ["birdpost"] = {
        label = "Bird Post",
        weight = 5,
        stack = true,
        close = true,
        description = "Bird Post for sending letters",
        client = {
            image = "birdpost.png",
            usetime = 2500
        },
    },
    ["fossil_stone"] = {
        label = "Stone Fossil",
        weight = 500,
        stack = true,
        close = true,
        description = "Archology Collectible",
        client = {
            image = "fossil_petoskey_stone.png",
            usetime = 2500
        },
    },
    ["medicine_quinine"] = {
        label = "Medicine Quinine",
        weight = 100,
        stack = true,
        close = true,
        description = "Antimalarial and fever reducer - specialized treatment",
        client = {
            image = "medicine_quinine.png",
            usetime = 2500
        },
    },
    ["consumable_moonshine_american"] = {
        label = "American Pride Moonshine",
        weight = 300,
        stack = true,
        close = true,
        description = "Classic American moonshine",
        client = {
            image = "consumable_moonshine_american.png",
            usetime = 2500
        },
    },
    ["predator_meat"] = {
        label = "Predator Meat",
        weight = 1000,
        stack = true,
        close = true,
        description = "Raw predator meat",
        degrade = 0.0033333333333333,
        client = {
            image = "provision_meat_mature.png"
        },
    },
    ["carrotseed"] = {
        label = "Carrot seed",
        weight = 0,
        stack = true,
        close = true,
        description = "Used in agriculture",
        client = {
            image = "seed_carrot.png",
            usetime = 2500
        },
    },
    ["trap_small"] = {
        label = "Small Animal Trap",
        weight = 500,
        stack = true,
        close = true,
        description = "Catches small animals",
        client = {
            image = "trap_small.png",
            usetime = 2500
        },
    },
    ["bone_shards"] = {
        label = "Bone Shards",
        weight = 10,
        stack = true,
        close = true,
        description = "Archology Collectible",
        client = {
            image = "bone_shards.png",
            usetime = 2500
        },
    },
    ["fossil_sea_lily"] = {
        label = "Sea Fossil",
        weight = 500,
        stack = true,
        close = true,
        description = "Archology Collectible",
        client = {
            image = "fossil_sea_lily.png",
            usetime = 2500
        },
    },
    ["horse_stimulant"] = {
        label = "Horse Stimulant",
        weight = 100,
        stack = true,
        close = true,
        description = "Given to horses",
        client = {
            image = "horse_stimulant.png",
            usetime = 2500
        },
    },
    ["small_pelt"] = {
        label = "Small Pelt",
        weight = 100,
        stack = true,
        close = true,
        description = "small animal pelt",
        client = {
            image = "small_pelt.png",
            usetime = 2500
        },
    },
    ["broccoliseed"] = {
        label = "Broccoli seed",
        weight = 0,
        stack = true,
        close = true,
        description = "Used in agriculture",
        client = {
            image = "seed_broccoli.png",
            usetime = 2500
        },
    },
    ["bolts"] = {
        label = "Bolts",
        weight = 10,
        stack = true,
        close = true,
        description = "Metal bolts for construction",
        client = {
            image = "bolts.png"
        },
    },
    ["fossil_pet_wood_rainbow"] = {
        label = "Wood Rainbow Fossil",
        weight = 1000,
        stack = true,
        close = true,
        description = "Archology Collectible",
        client = {
            image = "fossil_rainbow_petrified_wood.png",
            usetime = 2500
        },
    },
    ["consumable_mash"] = {
        label = "Basic Mash",
        weight = 500,
        stack = true,
        close = true,
        description = "Fermented mash ready for distillation",
        client = {
            image = "consumable_mash.png"
        },
    },
    ["p_finishedragonfly01x"] = {
        label = "Dragonfly Lure",
        weight = 10,
        stack = true,
        close = true,
        description = "used for fishing",
        degrade = 0.0033333333333333,
        client = {
            image = "p_finishedragonfly01x.png",
            usetime = 2500
        },
    },
    ["squirrel_meat"] = {
        label = "Squirrel Meat",
        weight = 150,
        stack = true,
        close = true,
        description = "Raw squirrel meat",
        degrade = 0.0033333333333333,
        client = {
            image = "provision_meat_exotic.png"
        },
    },
    ["muskrat"] = {
        label = "Muskrat",
        weight = 600,
        stack = true,
        close = true,
        description = "Muskrat carcass",
        client = {
            image = "muskrat.png"
        },
    },
    ["fossil_tooth_trex"] = {
        label = "Trex Tooth Fossil",
        weight = 40,
        stack = true,
        close = true,
        description = "Archology Collectible",
        client = {
            image = "fossil_tooth_front.png",
            usetime = 2500
        },
    },
    ["appleseed"] = {
        label = "Apple seed",
        weight = 0,
        stack = true,
        close = true,
        description = "Used in agriculture",
        client = {
            image = "seed_apple.png",
            usetime = 2500
        },
    },
    ["archeology_brush"] = {
        label = "Archeology Brush",
        weight = 10,
        stack = false,
        close = true,
        description = "Tool for archaeology sites",
        client = {
            image = "archeology_brush.png",
            usetime = 2500
        },
    },
    ["turtle_meat"] = {
        label = "Turtle Meat",
        weight = 400,
        stack = true,
        close = true,
        description = "Raw turtle meat",
        degrade = 0.0033333333333333,
        client = {
            image = "provision_meat_exotic.png"
        },
    },
    ["coffee"] = {
        label = "Coffee",
        weight = 100,
        stack = true,
        close = true,
        description = "Hot Coffee",
        degrade = 0.1,
        client = {
            image = "consumable_coffee.png",
            usetime = 2500
        },
    },
    ["horse_holster"] = {
        label = "Horse Holster",
        weight = 100,
        stack = true,
        close = true,
        description = "Somewhere to put your gun",
        client = {
            image = "horse_holster.png",
            usetime = 2500
        },
    },
    ["medicine_whiskey"] = {
        label = "Medicine Whiskey",
        weight = 100,
        stack = true,
        close = true,
        description = "Alcohol-based antiseptic and anesthetic - frontier medicine",
        client = {
            image = "medicine_whiskey.png",
            usetime = 2500
        },
    },
}
